name: Destroy Azure Resources

on:
  workflow_dispatch:    
    inputs:
        hub_rg_name:
            description: 'The hub resource group name'
            default: 'rg-hub-ai'
            required: true
            type: string
        spoke_ai_rg:
            description: 'The spoke with AI resource group name'
            default: 'rg-ai-shared-srv'
            required: true
            type: string            

jobs:
  destroy-azure-resources:

    env:
      AZURE_CORE_OUTPUT: 'none'      

    runs-on: ubuntu-latest

    steps:
      
      - name: Azure Login
        uses: Azure/login@v2        
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: destroy resources
        run: |
          az group delete --name ${{ inputs.hub_rg_name }} --yes --no-wait
          az group delete --name ${{ inputs.spoke_ai_rg }} --yes --no-wait
                        


    

# name: Destroy Resource Groups

# on:
#     workflow_dispatch:

# jobs:
#     destroy:
#         runs-on: ubuntu-latest

#         steps:

#         - name: Log in to Azure CLI
#             uses: azure/login@v1
#             with:
#                 creds: ${{ secrets.AZURE_CREDENTIALS }}

#         - name: Destroy Resource Group 1
#             run: az group delete --name <ResourceGroupName1> --yes --no-wait

#         - name: Destroy Resource Group 2
#             run: az group delete --name <ResourceGroupName2> --yes --no-wait